// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Location-0]
	_ = x[Measurement-1]
	_ = x[Alert-2]
	_ = x[StateChange-3]
	_ = x[CommandInvocation-4]
	_ = x[CommandResponse-5]
}

const _EventType_name = "LocationMeasurementAlertStateChangeCommandInvocationCommandResponse"

var _EventType_index = [...]uint8{0, 8, 19, 24, 35, 52, 67}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
