// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NewAssignment-0]
	_ = x[Location-1]
	_ = x[Measurement-2]
	_ = x[Alert-3]
	_ = x[StateChange-4]
	_ = x[CommandInvocation-5]
	_ = x[CommandResponse-6]
}

const _EventType_name = "NewAssignmentLocationMeasurementAlertStateChangeCommandInvocationCommandResponse"

var _EventType_index = [...]uint8{0, 13, 21, 32, 37, 48, 65, 80}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
